[[redirects]]
from="/*"
to= "/index.html"
status = 200  
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"